# Generated by Django 5.0.6 on 2024-06-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Air', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
